package(
    default_testonly = 1,
    default_visibility = ["//visibility:public"],
)

load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "bazel",
    srcs = ["bazel.go"],
)

go_library(
    name = "httphelper",
    srcs = ["http_helper.go"],
)

go_library(
    name = "portpicker",
    srcs = ["port_picker.go"],
)
