package(
    default_testonly = 1,
    default_visibility = ["//visibility:public"],
)

java_binary(
    name = "SeleniumServer",
    main_class = "org.openqa.grid.selenium.GridLauncherV3",
    runtime_deps = [
        "@selenium_server//jar",
    ],
)
