package(
    default_testonly = 1,
    default_visibility = ["//visibility:public"],
)

java_library(
    name = "util",
    srcs = glob(["*.java"]),
    deps = [
        "@com_google_guava_guava//jar",
    ],
)
