package(
    default_testonly = 1,
    default_visibility = ["//visibility:public"],
)

load("//web:web.bzl", "browser")

browser(
	name = "external",
	browser = "external",
	metadata = "external.json",
)